source 'https://rubygems.org'

ruby '2.6.10'

gem 'rails', '5.2.8.1'
gem 'sqlite3'
gem 'puma', '~> 3.11'
gem 'jbuilder', '~> 2.5'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '< 1.8.0'
gem 'rack-cors'
gem 'rspec-rails'
gem 'rubocop', require: false
gem 'devise-jwt', '0.9.0'
gem 'annotate'
gem 'will_paginate'
gem 'active_model_serializers', '~> 0.10.0'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'simplecov', require: false, group: :test

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
